services:
  db:
    image: postgres:17-alpine
    container_name: ecom_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ecom
      POSTGRES_PASSWORD: ecom_dev_password
      POSTGRES_DB: ecom
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
